name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.11","1.12","1.13","1.14"]

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: isbang/compose-action@v0.2.0
        with:
            compose-file: ./docker-compose.yml # optional, default is ./docker-compose.yml

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: dependency
        run: go get -u

      - name: Run test
        run: make test
